### PR TITLE
Add readthedocs automatic build

### PR DESCRIPTION
**Pull request by itziakos**
This PR add automatic builds in readthedocs for qt_binder. As a side effect, building the documentation does not need PySide or PyQt anymore.

see http://qt-binder.readthedocs.org/en/add-read-the-docs/

`note` I also use the new `trait_documenter` package from pip instead of the implementation inside traits.

### CODE REVIEW

**Comment by itziakos** [comment]
PR is ready for review

**Comment by rkern** [comment]
The `qt_binder.bounder_editor` API docs are missing: http://qt-binder.readthedocs.org/en/add-read-the-docs/api/bound_editor.html

They are present in my local build. A missing dependency in the `readthedocs_requirements.txt` causing the import to fail? Does `pyface` need to be there in addition to `traitsui`?

**Comment by itziakos** [comment]
I will have a look

**Comment by itziakos** [comment]
Found it in the readthedocs logs, there is an issue with the mocking mechanism. Will work on it later tonight

``` python
/home/docs/checkouts/readthedocs.org/user_builds/qt-binder/checkouts/add-read-the-docs/docs/source/api/bound_editor.rst:6: WARNING: autodoc: failed to import class u'Bound' from module u'qt_binder.bound_editor'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/qt-binder/envs/add-read-the-docs/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/home/docs/checkouts/readthedocs.org/user_builds/qt-binder/envs/add-read-the-docs/local/lib/python2.7/site-packages/qt_binder-0.1-py2.7.egg/qt_binder/bound_editor.py", line 19, in <module>
    from traitsui.qt4.editor import Editor
  File "/home/docs/checkouts/readthedocs.org/user_builds/qt-binder/envs/add-read-the-docs/local/lib/python2.7/site-packages/traitsui/qt4/editor.py", line 24, in <module>
    from traitsui.api \
  File "/home/docs/checkouts/readthedocs.org/user_builds/qt-binder/envs/add-read-the-docs/local/lib/python2.7/site-packages/traitsui/api.py", line 36, in <module>
    from .editors.api import ArrayEditor
  File "/home/docs/checkouts/readthedocs.org/user_builds/qt-binder/envs/add-read-the-docs/local/lib/python2.7/site-packages/traitsui/editors/__init__.py", line 23, in <module>
    from .api import ArrayEditor
  File "/home/docs/checkouts/readthedocs.org/user_builds/qt-binder/envs/add-read-the-docs/local/lib/python2.7/site-packages/traitsui/editors/api.py", line 24, in <module>
    from .code_editor import CodeEditor
  File "/home/docs/checkouts/readthedocs.org/user_builds/qt-binder/envs/add-read-the-docs/local/lib/python2.7/site-packages/traitsui/editors/code_editor.py", line 36, in <module>
    class ToolkitEditorFactory ( EditorFactory ):
  File "/home/docs/checkouts/readthedocs.org/user_builds/qt-binder/envs/add-read-the-docs/local/lib/python2.7/site-packages/traitsui/editors/code_editor.py", line 48, in ToolkitEditorFactory
    mark_color = Color( 0xECE9D8 )
  File "/home/docs/checkouts/readthedocs.org/user_builds/qt-binder/envs/add-read-the-docs/local/lib/python2.7/site-packages/traits/traits.py", line 489, in __call__
    return self.maker_function( *args, **metadata )
  File "/home/docs/checkouts/readthedocs.org/user_builds/qt-binder/envs/add-read-the-docs/local/lib/python2.7/site-packages/traits/traits.py", line 1203, in Color
    return ColorTrait( *args, **metadata )
  File "/home/docs/checkouts/readthedocs.org/user_builds/qt-binder/envs/add-read-the-docs/local/lib/python2.7/site-packages/traitsui/toolkit_traits.py", line 7, in ColorTrait
    return toolkit().color_trait( *args, **traits )
  File "/home/docs/checkouts/readthedocs.org/user_builds/qt-binder/envs/add-read-the-docs/local/lib/python2.7/site-packages/traitsui/qt4/toolkit.py", line 469, in color_trait
    import color_trait as ct
  File "/home/docs/checkouts/readthedocs.org/user_builds/qt-binder/envs/add-read-the-docs/local/lib/python2.7/site-packages/traitsui/qt4/color_trait.py", line 75, in <module>
    for name in QtGui.QColor.colorNames():
TypeError: 'DocMock' object is not iterable
```

**Comment by itziakos** [comment]
Done it should work now

**Comment by rkern** [comment]
LGreatTM!

**Pull request merged**
