### PR TITLE
Fix adding layouts to layout

### PR DESCRIPTION
**Pull request by pberkes**
Fix enthought/qt_binder#26

### CODE REVIEW

**Comment by rkern** [comment]
Thanks! Can you add a test with a `QSpacerItem()` to test the final branch?

**Comment by pberkes** [comment]
Will try: `SpacerItem` cannot be added as it is

```
======================================================================
ERROR: test_widget_inside_nested_layout_has_parent (qt_binder.tests.test_raw_widgets.TestBoxLayout)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/pberkes/egit/qt_binder/qt_binder/tests/test_raw_widgets.py", line 49, in test_widget_inside_nested_layout_has_parent
    box = GroupBox(VBoxLayout(VBoxLayout(label, SpacerItem())))
  File "/Users/pberkes/egit/qt_binder/qt_binder/binder.py", line 414, in __init__
    self._initialize_binder_class()
  File "/Users/pberkes/egit/qt_binder/qt_binder/binder.py", line 511, in _initialize_binder_class
    meta_object = qt_class.staticMetaObject
AttributeError: type object 'PySide.QtGui.QSpacerItem' has no attribute 'staticMetaObject'
```

**Comment by rkern** [comment]
Oh joy.

**Comment by pberkes** [comment]
I think I need to use `v_box_layout.addStretch()` or something like that

**Comment by rkern** [comment]
You can just drop the last branch, then. It looks like there is no reason at all for a `QLayoutItem()` to be represented as a `Binder`. (Though it would be nice to represent a spacer declaratively in the tree, but I can tackle that later.)

**Comment by rkern** [comment]
Ah, `QLayoutItem`s aren't even `QObject`s so it would never work as a `Binder`.

**Comment by pberkes** [comment]
I removed the LayoutItems

**Comment by rkern** [comment]
LGTM, thanks!

**Pull request merged**
