### PR TITLE
PyQt support

### LINKED ISSUE #18: Add support for PyQt
I'm looking into this...

### PR DESCRIPTION
**Pull request by jwiggins**
Adding qt import redirection from pyface. ~~This doesn't actually work yet, and `QUiLoader` needs to be implemented.~~

Closes #18

### CODE REVIEW

**Comment by jwiggins** [comment]
Ugh... I might need to rethink implementing `QUiLoader`. There's a pretty good work-around here: https://github.com/rossant/qtools/blob/master/qtools/qtpy/binding_helper.py

**Comment by jwiggins** [comment]
@rkern: My Qt skills are rusty and signals are being connected in a strange way. Is there a reason it was done like this?

**Comment by rkern** [comment]
Since we are getting the signals from the `QMetaObject`, there is less of an impedance mismatch with this "old" style of connecting up, which is much closer to the C++ style. The "new" style of signals is much better when you are manually connecting them up, but for automated construction by introspection, this is better. Especially in the case of overloading.

The root of the problem is that PyQt4 defines the `QObject.dis/connect()` methods as classmethods rather than instancemethods as in PySide, so we need to change these to `QtCore.QObject.connect(qobj, self.signal, slot)` etc. Then it works.

Now I just need to find out why the `TextField` doesn't get a `validator`...

**Comment by rkern** [comment]
Huh, `callable(PyQt4.QtGui.QLineEdit.setValidator) is False`.

**Comment by jwiggins** [comment]
natch

**Comment by rkern** [comment]
I'd like to import the `GuiTestAssistant` for use here. It looks like PyQt4 (or at least the version I have) can't construct some `QWidgets` at all without a `QApplication` running while PySide can.

```
test_composite (qt_binder.tests.test_binder.TestBinder) ... QWidget: Must construct a QApplication before a QPaintDevice
```

**Comment by rkern** [comment]
I'll work on that on Monday unless of someone beats me to it.

https://github.com/enthought/pyface/blob/master/pyface/ui/qt4/util/gui_test_assistant.py

**Comment by jwiggins** [comment]
Yeah, I haven't been able to run the tests at all locally due to that problem. I'll see what I can do. Thanks for the assist!

**Comment by rkern** [comment]
Hmm, we're already creating a `QApplication` in `TestBinder.setUp()`.

**Comment by jwiggins** [comment]
Right. The only way I could run the tests without them crashing immediately was to comment out the last two tests in `test_binder.py` Your last change appears to fix the problem.

**Comment by itziakos** [comment]
I added testing using PyQt. It looks there is some problem with importing `sip`. I am investigating

**Comment by mchilvers** [comment]
Is 'unvestigating' in the same vein as 'misunderestimating'? :)

**Comment by itziakos** [comment]
spelling error corrected

**Comment by rkern** [comment]
Add `python-sip`?

**Comment by itziakos** [comment]
> Add python-sip?

The strange thing is that python-sip is already installed https://travis-ci.org/enthought/qt_binder/jobs/79093827#L99

**Comment by itziakos** [comment]
I think, I found the problem. need to just work out how to setup travis-ci

**Comment by itziakos** [comment]
Done, PyQt tests are running on 2.7 (we need to rebuild PyQt for python 3.4 which is not trivial). I think that for now it is ok. 
Please note that the tests are currently failing

**Comment by jwiggins** [comment]
Thanks for breaking the build @itziakos :smile: 

The good new is that those are the same failures I see when running the tests locally.

**Comment by rkern** [comment]
Progress!

**Comment by rkern** [comment]
We should clean up the UI after the `edit_traits()` properly. The `GuiTestAssistant` helps with that. After we do that, this PR should be good to go.

**Comment by jwiggins** [comment]
That should have it then, no?

**Comment by rkern** [comment]
Indeed. I got distracted by other work while waiting for the CI to finish. :-)

Thank you!

**Pull request merged**
